### ISSUE TITLE
cannot reset mxadmin password using "$ADMIN_PASSWORD"

### ISSUE THREAD

**Issue by basi01** [mendix/cf-mendix-buildpack#467]
I needed to test something and connected to the app db from Studio. For some reason Studio had set MxAdmin password to "1". Now the app fails to start in the container with the message:

     2021-09-12T13:04:12.16+0300 [APP/PROC/WEB/0] ERR ERROR: Executing start did not succeed: result: 5, message: Using password '1' for a user with administrator user roles is not allowed. The following admin users have password 1: [MxAdmin]

despite having a conforming `$ADMIN_PASSWORD` in `cf env` for the app.

https://github.com/mendix/cf-mendix-buildpack/blob/ee3008d04545070803e7ce3f35124318e39def47/README.md

> Similarly, the setting can be used to reset the password of an administrator.

Doesn't seem so.

**Comment by jeohist** [comment]
Hi @basi01, is the M2EE_PASSWORD environment variable set? If it's set, the MxAdmin user will not be created (https://github.com/mendix/cf-mendix-buildpack/blob/ee3008d04545070803e7ce3f35124318e39def47/buildpack/runtime_components/security.py#L28-L41). 
If this is the case for you, we should update our readme to make this clearer.

**Comment by basi01** [comment]
Hi. M2EE_PASSWORD is not set.

**Comment by markbastiaans** [comment]
Hi @basi01 - this seems to be a classic Catch-22 situation: the runtime fails to start due to the invalid password, which makes it impossible to change it to something that works, since that can only be done if the runtime has been started.

Unfortunately, this is not something we can solve in the buildpack, since this seems to be an issue with the Mendix runtime. I recommend that you raise an issue with Mendix Support so that this issue ends up at the relevant team(s) for troubleshooting.
