### ISSUE TITLE
App crashing after a day of working. 

### ISSUE THREAD

**Issue by cfmagnum** [mendix/cf-mendix-buildpack#84]
Hi,

This is issue is related to https://github.com/mendix/cf-mendix-buildpack/issues/78.

When i keep on running https://github.com/mendix/MxPushNotifications/tree/master/test for more then one day app is getting crashed on hitting the URL.
![screen shot 04-10-17 at 11 54 am](https://cloud.githubusercontent.com/assets/13657881/24848606/2c65357a-1de5-11e7-8272-14058284082b.PNG)

In logs we can see:
![screen shot 04-10-17 at 12 01 pm](https://cloud.githubusercontent.com/assets/13657881/24848683/8b602dbe-1de5-11e7-8e48-5ed28360e7c1.PNG)

When i tried to restart the app 

![screen shot 04-10-17 at 12 05 pm](https://cloud.githubusercontent.com/assets/13657881/24848763/05a5f0ae-1de6-11e7-8784-570dfc72d4a3.PNG)
![screen shot 04-10-17 at 12 05 pm 001](https://cloud.githubusercontent.com/assets/13657881/24848766/07e10bc4-1de6-11e7-99f3-b03620cc037b.PNG)

After that i am not able to delete the app or unbind the app from its service instance.

when i tried to unbind the app from the service instance.

![screen shot 04-10-17 at 12 07 pm](https://cloud.githubusercontent.com/assets/13657881/24848826/5797d2b0-1de6-11e7-938f-746cac3745c5.PNG)

And when i try to delete app its gives error
![screen shot 04-10-17 at 12 09 pm](https://cloud.githubusercontent.com/assets/13657881/24848858/82435048-1de6-11e7-8539-95cb8dcad25c.PNG)

**Comment by djvdorp** [comment]
Hi,

Your [first screenshot](https://cloud.githubusercontent.com/assets/13657881/24848606/2c65357a-1de5-11e7-8272-14058284082b.PNG) shows the `nginx 502 Bad Gateway` that likely indicates that the Mendix Runtime is either not running healthy or not responding, also seen in the logs from your [second screenshot](https://cloud.githubusercontent.com/assets/13657881/24848683/8b602dbe-1de5-11e7-8e48-5ed28360e7c1.PNG).

However, what exactly is causing this is not trivial to pinpoint at this point. Your [third screenshot](https://cloud.githubusercontent.com/assets/13657881/24848763/05a5f0ae-1de6-11e7-8784-570dfc72d4a3.PNG) seems to indicate that the Mendix Runtime is unable to connect to the database:

```
[..]
WARNING - ConnectionBus: Database connections: 0 active, 0 idle.
ERROR - ConnectionBus: Opening JDBC connection to Some(10.0.11.100:5435) failed with SQLState: 42501 Error code: 0 Message: FATAL: permission denied for database "d0813decb_c00e_4af7_afc0_9b0b19d69737"
  Detail: User does not have CONNECT privilege. Retrying...(1/4)
[..]
ERROR - M2EE: An error occurred while initializing the Runtime
[..]
ERROR: Executing start did not succeed: result: 1, message: An error occurred while initializing the Runtime, caused by: com.mendix.connectionbus.ConnectionBusRuntimeException: Error on initializing database connection.
[..]
WARNING: start failed, stopping
```

This can also be seen in your [fourth screenshot](https://cloud.githubusercontent.com/assets/13657881/24848766/07e10bc4-1de6-11e7-99f3-b03620cc037b.PNG) where it says:

```
[..]
Caused by: com.mendix.connectionbus.ConnectionBusRuntimeException: Error on initializing database connection.
  at com.mendix.connectionbus.ConnectionBusInitializer.throwDefault$1(ConnectionBusInitializer.scala:61)
Caused by: org.postgresql.util.PSQLException: FATAL: permission denied for database "d0813decb_c00e_4af7_afc0_9b0b19d69737"
  Detail: User does not have CONNECT privilege.
WARNING: start failed, stopping
[..]
```

Both these screenshot seem to point in the direction that the database that you are trying to use for deploying this Mendix app might not be stable, as the Mendix Runtime is unable to access the database it is unable to run (or keep on running) and thus stops functioning, showing the `nginx 502 Bad Gateway` in your browser and the errors that you see in the Cloud Foundry logs.

Since you are also unable to unbind your database service ([fifth screenshot](https://cloud.githubusercontent.com/assets/13657881/24848826/5797d2b0-1de6-11e7-938f-746cac3745c5.PNG)) and to delete the app ([sixth screenshot](https://cloud.githubusercontent.com/assets/13657881/24848858/82435048-1de6-11e7-8539-95cb8dcad25c.PNG)) because of a Database error, I would recommend you to either check the stability of the backend database service and service broker yourself (if you are hosting the Cloud Foundry cluster yourself) or asking your Cloud Foundry service provider to look into this database stability issue, as I am afraid there is very little that we can do regarding this aspect of your CF cluster as it also doesn't seem like a Mendix or buildpack-specific issue from the information supplied.

**Comment by cfmagnum** [comment]
Thanks for the help.

But what i can see is that the app is running for more that 12 hours ,after that it is showing this error.IN between that time we have not changed anything into the database or deleted any user.

**Comment by jtwaleson** [comment]
If unbind and delete app also don't work, I think the problem is with the cloud foundry cluster or with the service broker. I don't think the Mendix Runtime / Buildpack are the issue here. I'd ask your CF admins for help. Please re-open this issue if you can pinpoint the problem to the Mendix buildpack.
